In [14]:
"WEEK 1"

'WEEK 1'

In [15]:
cars = ['porshe' , 'mahindra' , 'tata' ]
cars[2] = 'bmw'
print(cars)

numbers = [10,20,30,40,50,60]
numbers.append(2)
numbers.insert(0,66)
print(numbers)


print('length , max , min of numbers respectively = ',len(numbers),
max(numbers),
min(numbers))

for i in numbers :
   print(i)



['porshe', 'mahindra', 'bmw']
[66, 10, 20, 30, 40, 50, 60, 2]
length , max , min of numbers respectively =  8 66 2
66
10
20
30
40
50
60
2


In [16]:
for i in range(len(numbers)):
   print(i,numbers[i])

0 66
1 10
2 20
3 30
4 40
5 50
6 60
7 2


In [17]:
evens=[x for x in numbers if x%2 == 0]
print(evens)

[66, 10, 20, 30, 40, 50, 60, 2]


In [18]:
squares=[x**2 for x in numbers]
print(squares)

[4356, 100, 400, 900, 1600, 2500, 3600, 4]


In [19]:
newlist = [x for x in range(20) ]
print(newlist)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [20]:
evensinnewlist = [x for x in newlist if x % 2 == 0 ]
print(evensinnewlist)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [21]:
odds = [x for x in newlist if x % 2 != 0 ]
print(odds)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [22]:
squaredevens=[x**2 for x in evensinnewlist ]
print(squaredevens)

[0, 4, 16, 36, 64, 100, 144, 196, 256, 324]


In [23]:
list2 = [0,0,0,2,3,5,4,0,0,0]
list2=[ x for x in list2 if x!=0]+[x for x in list2 if x==0]
print(list2)

[2, 3, 5, 4, 0, 0, 0, 0, 0, 0]


In [24]:
n = 10
a,b =0,1
fib = [a,b]
for i in range(n-2):
  c=a+b
  fib.append(c)
  a=b
  b=c
print(fib)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


In [25]:
n1 = int(input("Enter any number = "))
sum = 0
temp = n1
digits = len(str(n1))

while temp > 0 :
  dig = temp%10
  sum= sum + dig**digits
  temp = temp // 10

if sum == n1 :
   print("armstrong number")
else :
  print("not an armstrong number")


armstrong number


In [26]:
newtuple = ( 29,40,50 )
print(newtuple[1])

40


In [27]:
user = ("Suhaib", 22 ,"Data Science Intern")
def iQuasar_user():
  return user

name , age , position = iQuasar_user()
print(name , age , position)
print(name)
print(age)
print(position)
print(user[1])

Suhaib 22 Data Science Intern
Suhaib
22
Data Science Intern
22


In [28]:
x = ( 2 , 4)
y = (3 , 5)
x,y = y,x
print(x,y)

(3, 5) (2, 4)


In [29]:
s1 = {1,3,3,3,5,6,8,4,6,8,3,3}
s1.add(9)
s1.remove(6)
print(s1)

s2 = {4,9,6,7,0,8,5,3,2,5,3,6}
print("union of s1 and s2 = " , s2.union(s1))
print("intersection of s1 and s2 = " , s2.intersection(s1))
print("difference of s1 and s2 = " , s2.difference(s1))
print(s1|s2)


{1, 3, 4, 5, 8, 9}
union of s1 and s2 =  {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
intersection of s1 and s2 =  {3, 4, 5, 8, 9}
difference of s1 and s2 =  {0, 2, 6, 7}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}


In [30]:
mydict =[ {'name' : 'Suhaib' , 'age' : 22 , 'position' : 'Data Science Intern' },
         { 'name2' : 'Musaib' , 'age' : 22 ,'position' : 'Data Science Intern' } ]
print(mydict[0])
mydict[0]['age'] = 25
print(mydict)  
mydict.remove(mydict[1])
print(mydict)

{'name': 'Suhaib', 'age': 22, 'position': 'Data Science Intern'}
[{'name': 'Suhaib', 'age': 25, 'position': 'Data Science Intern'}, {'name2': 'Musaib', 'age': 22, 'position': 'Data Science Intern'}]
[{'name': 'Suhaib', 'age': 25, 'position': 'Data Science Intern'}]


In [31]:
import numpy as np
arr0= np.array([2 , 4 , 4 , 9 , 6])
arr1= np.array([2 , 3 , 4 , 5 , 6])
arr2= np.array([[2 , 3 , 4 , 5 , 6],[3 ,4 ,5 ,6 ,7]])
arr3= np.array([[2 , 3 , 4 , 5 , 6],[3 ,4 ,5 ,6 ,7], [5 ,6, 7, 3 , 8 ]])
          

In [32]:
arradd = arr1 + 5
arradd1 = arr0 + arr1
print("Array after adding 5 to each element: ", arradd)
print("Array after adding two arrays : " ,arradd1)

Array after adding 5 to each element:  [ 7  8  9 10 11]
Array after adding two arrays :  [ 4  7  8 14 12]


In [33]:
arrsub = arr1 - 5
arrsub1 = arr0 - arr1
print("Array after subtracting 5 from each element: ", arrsub)
print("Array after subtracting two arrays : " ,arrsub1)

Array after subtracting 5 from each element:  [-3 -2 -1  0  1]
Array after subtracting two arrays :  [0 1 0 4 0]


In [34]:
arrmul = arr1 * 5
arrsub1 = arr0 * arr1
print("Array after multiplying 5 to each element: ", arrmul)
print("Array after multiplying two arrays : " ,arrsub1)

Array after multiplying 5 to each element:  [10 15 20 25 30]
Array after multiplying two arrays :  [ 4 12 16 45 36]


In [35]:
arrdiv = arr1 // 2
arrdiv1 = arr0 // arr1
print("Array after dividing 2 from each element: ", arrdiv)
print("Array after dividing two arrays : " ,arrdiv1)

Array after dividing 2 from each element:  [1 1 2 2 3]
Array after dividing two arrays :  [1 1 1 1 1]


In [36]:
arrexp = arr1**3
print("Array after raising to power 3  : ", arrexp)


Array after raising to power 3  :  [  8  27  64 125 216]


In [37]:
arr1 + arr2

array([[ 4,  6,  8, 10, 12],
       [ 5,  7,  9, 11, 13]])

In [38]:
print(arr1)
arr1[2]= 6 
print(arr1)

[2 3 4 5 6]
[2 3 6 5 6]


In [39]:
arr2[0,3]

5

In [40]:
print(arr2)
arr2[0,3]= 10
print("updated array:", arr2)

[[2 3 4 5 6]
 [3 4 5 6 7]]
updated array: [[ 2  3  4 10  6]
 [ 3  4  5  6  7]]


In [41]:
arr1[:-1]

array([2, 3, 6, 5])

In [42]:
arr2[1,2:-2]

array([5])

In [43]:
arr2.shape
print(arr2)

[[ 2  3  4 10  6]
 [ 3  4  5  6  7]]


In [44]:
arr2.reshape(5,2)

array([[ 2,  3],
       [ 4, 10],
       [ 6,  3],
       [ 4,  5],
       [ 6,  7]])

In [45]:
print(np.mean(arr3))
print(np.median(arr3))
print(np.max(arr3))
print(np.min(arr3))

4.933333333333334
5.0
8
2


In [46]:

print("Original array:", arr3)
print("Ascending order sorting:", np.sort(arr3))
print("Descending order sorting:", np.sort(arr3)[::-1])

Original array: [[2 3 4 5 6]
 [3 4 5 6 7]
 [5 6 7 3 8]]
Ascending order sorting: [[2 3 4 5 6]
 [3 4 5 6 7]
 [3 5 6 7 8]]
Descending order sorting: [[3 5 6 7 8]
 [3 4 5 6 7]
 [2 3 4 5 6]]


In [47]:

print("Original array:", arr2)
print("Ascending order sorting:", np.sort(arr2))
print("Descending order sorting:", np.sort(arr2)[::-1])

Original array: [[ 2  3  4 10  6]
 [ 3  4  5  6  7]]
Ascending order sorting: [[ 2  3  4  6 10]
 [ 3  4  5  6  7]]
Descending order sorting: [[ 3  4  5  6  7]
 [ 2  3  4  6 10]]


In [48]:
print(np.any(arr3 > 5))
print(np.all(arr3 > 5))
print(arr0 == arr1)
print(arr0 != arr3)

True
False
[ True False False False  True]
[[False  True False  True False]
 [ True False  True  True  True]
 [ True  True  True  True  True]]


In [49]:
print(arr3)
mask = arr3 > 5
updated = arr3[mask]
print("Elements greater than 5 are :", updated)

[[2 3 4 5 6]
 [3 4 5 6 7]
 [5 6 7 3 8]]
Elements greater than 5 are : [6 6 7 6 7 8]


In [50]:
arr4= np.array([[2 , 3 , 4],[3 ,4 ,5 ]])
arr5= np.array([[2 , 4 , 3 ],[3 ,4 ,9 ]])
print(np.dot(arr0 , arr1))
print(np.cross(arr4 , arr5))


121
[[ -7   2   2]
 [ 16 -12   0]]


In [51]:
arr6 = np.array([[2, 1],
                 [1, 3]])

print("inverse of arr6:", np.linalg.inv(arr6))
print("determinant of arr6:", np.linalg.det(arr6))
eigenvalues , eigenvector =(np.linalg.eigvals(arr6))
print("eigenvector:", eigenvector)
print("eigenvalues:", eigenvalues)

print("rank of arr6:", np.linalg.matrix_rank(arr6))
print("Trace of arr6:", np.trace(arr6))

inverse of arr6: [[ 0.6 -0.2]
 [-0.2  0.4]]
determinant of arr6: 5.000000000000001
eigenvector: 3.618033988749895
eigenvalues: 1.381966011250105
rank of arr6: 2
Trace of arr6: 5


In [52]:
import pandas as pd

data = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])
print(data)


a    10
b    20
c    30
d    40
e    50
dtype: int64


In [53]:
data_frame = pd.DataFrame({
    'Name': ['Suhaib', 'Musaib', 'Rasikh', 'Mubashir', 'Akeel', 'Muzamil'],
    'Age': [22, 22, 21, 23, 24, 25],
    'Position': ['Data Science Intern', 'Data Science Intern', 'Data Science Intern', 'Data Science Intern', 'Data Science Intern', 'Data Science Intern']
})
df = pd.DataFrame(data_frame)
df

Name  Age             Position
0    Suhaib   22  Data Science Intern
1    Musaib   22  Data Science Intern
2    Rasikh   21  Data Science Intern
3  Mubashir   23  Data Science Intern
4     Akeel   24  Data Science Intern
5   Muzamil   25  Data Science Intern

In [54]:
df.head()

Name  Age             Position
0    Suhaib   22  Data Science Intern
1    Musaib   22  Data Science Intern
2    Rasikh   21  Data Science Intern
3  Mubashir   23  Data Science Intern
4     Akeel   24  Data Science Intern

In [55]:
df.tail()

Name  Age             Position
1    Musaib   22  Data Science Intern
2    Rasikh   21  Data Science Intern
3  Mubashir   23  Data Science Intern
4     Akeel   24  Data Science Intern
5   Muzamil   25  Data Science Intern

In [56]:
df.describe()

Age
count   6.000000
mean   22.833333
std     1.471960
min    21.000000
25%    22.000000
50%    22.500000
75%    23.750000
max    25.000000

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Name      6 non-null      object
 1   Age       6 non-null      int64 
 2   Position  6 non-null      object
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes


In [58]:
df.columns

Index(['Name', 'Age', 'Position'], dtype='object')

In [59]:
df.shape

(6, 3)

In [60]:
df["Age"]

0    22
1    22
2    21
3    23
4    24
5    25
Name: Age, dtype: int64

In [61]:
df[['Name','Position']]

Name             Position
0    Suhaib  Data Science Intern
1    Musaib  Data Science Intern
2    Rasikh  Data Science Intern
3  Mubashir  Data Science Intern
4     Akeel  Data Science Intern
5   Muzamil  Data Science Intern

In [62]:
df[df['Name'] == 'Suhaib']

Name  Age             Position
0  Suhaib   22  Data Science Intern

In [63]:
df[df['Age'] > 22]

Name  Age             Position
3  Mubashir   23  Data Science Intern
4     Akeel   24  Data Science Intern
5   Muzamil   25  Data Science Intern

In [64]:
df.iloc[1]


Name                     Musaib
Age                          22
Position    Data Science Intern
Name: 1, dtype: object

In [65]:
df.loc[4]

Name                      Akeel
Age                          24
Position    Data Science Intern
Name: 4, dtype: object

In [66]:
df['Eligiblity']= df['Age'] > 20
df

Name  Age             Position  Eligiblity
0    Suhaib   22  Data Science Intern        True
1    Musaib   22  Data Science Intern        True
2    Rasikh   21  Data Science Intern        True
3  Mubashir   23  Data Science Intern        True
4     Akeel   24  Data Science Intern        True
5   Muzamil   25  Data Science Intern        True

In [67]:
df.to_csv('iQuasar_interns.csv')